name: release

on:
  push:
    tags:
      - "*"

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: ./.github/workflows/build-and-upload.yml
    secrets: inherit
    permissions:
      packages: write
      contents: write
